# Generated by Django 6.0.4 on 2026-06-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_sub_profile',
            field=models.BooleanField(default=False, help_text='True if this user is a salon employee sub-profile account.'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='parent_salon',
            field=models.ForeignKey(blank=True, help_text='The salon owner who created this sub-profile.', limit_choices_to={'is_sub_profile': False, 'role': 'salon'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
