# Generated by Django 6.0.4 on 2026-05-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairStyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('wedding', 'Wedding'), ('party', 'Party'), ('business', 'Business'), ('date', 'Date Night'), ('everyday', 'Everyday')], default='everyday', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recommendations/categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hair Style Category',
                'verbose_name_plural': 'Hair Style Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StyleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='recommendations/references/')),
                ('suggested_products', models.TextField(blank=True, default='', help_text='Product recommendations as text')),
                ('suggested_treatments', models.TextField(blank=True, default='', help_text='Treatment recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Style Recommendation',
                'verbose_name_plural': 'Style Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recommendations/client_images/')),
                ('hair_length', models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_images', to='profiles.barberprofile')),
            ],
            options={
                'verbose_name': 'Client Image',
                'verbose_name_plural': 'Client Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
