# Generated by Django 6.0.4 on 2026-05-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
        ('recommendations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientimage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stylerecommendation',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.barberprofile'),
        ),
        migrations.AddField(
            model_name='stylerecommendation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.hairstylecategory'),
        ),
        migrations.AddField(
            model_name='stylerecommendation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stylerecommendation',
            name='client_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='recommendations.clientimage'),
        ),
        migrations.AddField(
            model_name='stylerecommendation',
            name='suggested_services',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='services.service'),
        ),
    ]
