# Generated by Django 6.0.4 on 2026-05-04 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/barbers/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/barbers/covers/')),
                ('bio', models.TextField(blank=True, default='')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('category', models.CharField(choices=[('barber', 'Barber'), ('hairdresser', 'Hairdresser'), ('stylist', 'Stylist'), ('colorist', 'Colorist'), ('braider', 'Braider'), ('unisex', 'Unisex Salon')], db_index=True, default='barber', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_badge', models.CharField(blank=True, default='', max_length=50)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Working hours by day: {"monday": {"open": "09:00", "close": "18:00"}, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barber Profile',
                'verbose_name_plural': 'Barber Profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/clients/avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('hair_type', models.CharField(blank=True, choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], default='', max_length=20)),
                ('preferred_hair_length', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='Stylist', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/employees/avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('specialties', models.TextField(blank=True, default='', help_text='Comma-separated list of specialties')),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_bookings', models.BooleanField(default=True)),
                ('can_manage_schedule', models.BooleanField(default=True)),
                ('can_access_tools', models.BooleanField(default=True)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_delete_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
            },
        ),
    ]
