# Generated by Django 6.0.4 on 2026-05-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'barber'}, on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='profiles.barberprofile'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='barberprofile',
            index=models.Index(fields=['city', 'is_verified'], name='profiles_ba_city_f62fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='barberprofile',
            index=models.Index(fields=['average_rating'], name='profiles_ba_average_9528cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('barber', 'user')},
        ),
    ]
