# Generated by Django 6.0.4 on 2026-06-02 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='experience_range',
            field=models.CharField(blank=True, choices=[('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], default='', help_text='Experience range selection from profile setup', max_length=10),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='gallery_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/barbers/gallery/'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='role_title',
            field=models.CharField(blank=True, default='Barber', help_text='Professional role: Barber, Hair Stylist, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='List of specialty tags, e.g. ["Fades", "Braids", "Perms"]'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='List of working days, e.g. ["M", "T", "W", "T", "F", "S", "S"]'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='About you / what makes you unique'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Working hours: {"opening_time": "09:00", "opening_period": "AM", "closing_time": "06:00", "closing_period": "PM"}'),
        ),
        migrations.CreateModel(
            name='SalonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/salons/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/salons/covers/')),
                ('bio', models.TextField(blank=True, default='')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('experience_range', models.CharField(blank=True, choices=[('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], default='', max_length=10)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_badge', models.CharField(blank=True, default='', max_length=50)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('working_days', models.JSONField(blank=True, default=list, help_text='List of working days, e.g. ["M", "T", "W", "T", "F", "S", "S"]')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='Working hours: {"opening_time": "09:00", "opening_period": "AM", "closing_time": "06:00", "closing_period": "PM"}')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('gallery_image_5', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('gallery_image_6', models.ImageField(blank=True, null=True, upload_to='profiles/salons/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_sub_profile': False, 'role': 'salon'}, on_delete=django.db.models.deletion.CASCADE, related_name='salon_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon Profile',
                'verbose_name_plural': 'Salon Profiles',
            },
        ),
        migrations.CreateModel(
            name='SalonEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_email', models.EmailField(help_text='Auto-generated login email (firstname+lastname+2digits@hairlync.app)', max_length=254, unique=True)),
                ('generated_password', models.CharField(help_text='Auto-generated 8-character password (stored for display to salon owner)', max_length=8)),
                ('position', models.CharField(blank=True, default='Hair Stylist', max_length=100)),
                ('role_title', models.CharField(blank=True, default='Hair Stylist', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/employees/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/employees/covers/')),
                ('bio', models.TextField(blank=True, default='')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='List of specialty tags, e.g. ["Fades", "Braids", "Perms"]')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('experience_range', models.CharField(blank=True, choices=[('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], default='', max_length=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='profiles.salonprofile')),
            ],
            options={
                'verbose_name': 'Salon Employee',
                'verbose_name_plural': 'Salon Employees',
            },
        ),
    ]
