# Generated by Django 6.0.4 on 2026-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_employee_alter_timeslot_employee'),
        ('profiles', '0003_alter_employeeprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.AddIndex(
            model_name='salonprofile',
            index=models.Index(fields=['city', 'is_verified'], name='profiles_sa_city_45a419_idx'),
        ),
        migrations.AddIndex(
            model_name='salonprofile',
            index=models.Index(fields=['average_rating'], name='profiles_sa_average_109658_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salonemployee',
            unique_together={('salon', 'user')},
        ),
    ]
