# Generated by Django 6.0.4 on 2026-07-09 03:45

import Apps.profiles.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_employeeprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Apps.profiles.models.profile_service_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='profiles.barberprofile')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='profiles.salonemployee')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_services', to='profiles.salonprofile')),
            ],
            options={
                'verbose_name': 'Service Management',
                'verbose_name_plural': 'Service Management',
                'ordering': ['service_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', False), ('employee__isnull', True), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('employee__isnull', True), ('salon__isnull', False)), models.Q(('barber__isnull', True), ('employee__isnull', False), ('salon__isnull', True)), _connector='OR'), name='profiles_service_one_owner'), models.UniqueConstraint(condition=models.Q(('barber__isnull', False)), fields=('barber', 'service_name'), name='unique_barber_profile_service'), models.UniqueConstraint(condition=models.Q(('salon__isnull', False)), fields=('salon', 'service_name'), name='unique_salon_profile_service'), models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('employee', 'service_name'), name='unique_employee_profile_service')],
            },
        ),
    ]
