# Generated by Django 6.0.4 on 2026-07-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_employeeprofile_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_employees',
            field=models.ManyToManyField(blank=True, help_text='Salon services only. Empty means every active salon employee may provide it.', related_name='available_services', to='profiles.salonemployee'),
        ),
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(blank=True, help_text='Set for salon services. Null for barber services.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.salonprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barber',
            field=models.ForeignKey(blank=True, help_text='Set for barber services. Null for salon services.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.barberprofile'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', False), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('salon__isnull', False)), _connector='OR'), name='service_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('salon__isnull', False)), fields=('salon', 'name'), name='uniq_salon_service_name'),
        ),
    ]
