# Generated by Django 6.0.4 on 2026-05-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('profiles', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='profiles.employeeprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.service'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.barberprofile'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.employeeprofile'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='bookings_bo_status_c5c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['barber', 'date'], name='bookings_bo_barber__0b0fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status'], name='bookings_bo_client__09b1d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('barber', 'date', 'start_time')},
        ),
    ]
