# Generated by Django 6.0.4 on 2026-07-15 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_employee_alter_timeslot_employee'),
        ('profiles', '0004_delete_employeeprofile_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='salon',
            field=models.ForeignKey(blank=True, help_text='Set for salon bookings. Null for barber bookings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.salonprofile'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='salon',
            field=models.ForeignKey(blank=True, help_text='Set for salon availability. Null for barber availability.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.salonprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='barber',
            field=models.ForeignKey(blank=True, help_text='Set for barber bookings. Null for salon bookings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.barberprofile'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='barber',
            field=models.ForeignKey(blank=True, help_text='Set for barber availability. Null for salon availability.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.barberprofile'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'date'], name='bookings_bo_salon_i_544e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['salon', 'status'], name='bookings_bo_salon_i_9a28dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['employee', 'date'], name='bookings_bo_employe_15f81b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['employee', 'date'], name='bookings_ti_employe_2c1f67_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['salon', 'date'], name='bookings_ti_salon_i_8c668f_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', False), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('salon__isnull', False)), _connector='OR'), name='booking_exactly_one_business'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('salon__isnull', True), ('employee__isnull', False), _connector='OR'), name='booking_salon_requires_employee'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', False), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('salon__isnull', False)), _connector='OR'), name='timeslot_exactly_one_business'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('salon__isnull', True), ('employee__isnull', False), _connector='OR'), name='timeslot_salon_requires_employee'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(condition=models.Q(('salon__isnull', False)), fields=('employee', 'date', 'start_time'), name='uniq_salon_employee_slot'),
        ),
    ]
