# Generated by Django 6.0.4 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('guide', 'Guide'), ('article', 'Article'), ('tutorial', 'Tutorial')], default='article', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='', help_text='Full content body (for articles/guides)')),
                ('video_url', models.URLField(blank=True, default='', help_text='Video URL (YouTube, Vimeo, etc.)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='education/thumbnails/')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Duration for videos in minutes')),
                ('is_premium', models.BooleanField(default=True, help_text='Requires active subscription to access')),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educational Content',
                'verbose_name_plural': 'Educational Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education Category',
                'verbose_name_plural': 'Education Categories',
                'ordering': ['name'],
            },
        ),
    ]
