# Generated by Django 6.0.4 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before/')),
                ('category', models.CharField(choices=[('haircut', 'Haircut'), ('coloring', 'Coloring'), ('styling', 'Styling'), ('treatment', 'Treatment'), ('braiding', 'Braiding'), ('beard', 'Beard'), ('other', 'Other')], default='haircut', max_length=20)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
