# Generated by Django 6.0.4 on 2026-07-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
        ('profiles', '0005_add_lat_lon_to_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='owner_type',
            field=models.CharField(choices=[('barber', 'Barber'), ('salon', 'Salon'), ('salon_employee', 'Salon Employee')], default='barber', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.salonprofile'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='salon_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.salonemployee'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.barberprofile'),
        ),
    ]
